apiVersion: v2
name: shogun
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0
dependencies:
  - name: postgis
    version: "2.0.0"
    repository: "https://terrestris.github.io/helm-charts"
    condition: postgis.enabled
  - name: geoserver
    version: "2.1.0"
    repository: "https://terrestris.github.io/helm-charts"
    condition: geoserver.enabled
  - name: keycloak
    version: "18.7.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled
  - name: shogun-boot
    version: "*"
    condition: shogun-boot.enabled
  - name: shogun-admin
    version: "*"
    condition: shogun-admin.enabled
  - name: shogun-client
    version: "*"
    condition: shogun-client.enabled
  - name: mapfish-print
    version: "2.0.0"
    repository: "https://terrestris.github.io/helm-charts"
    condition: mapfish-print.enabled
  # Disabled for now
  # - name: gnos
  #   version: "0.1.0"
  #   repository: "https://terrestris.github.io/helm-charts"
  #   condition: gnos.enabled
