shogun-admin:
  enabled: true
  ingress:
    enabled: true
    className: ""
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: shogun.local
        paths:
          - path: /admin(/|$)(.*)
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: shogun-tls
    #    hosts:
    #      - shogun.local
  geoserver:
    url: "http://shogun.local/geoserver"
  keycloak:
    host: "shogun.local/keycloak"
  shogun:
    base: /shogun-boot

shogun-boot:
  enabled: true
  ingress:
    enabled: true
    className: ""
    annotations: { }
    # spec.ingressClassName: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: shogun.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [ ]
    #  - secretName: shogun-tls
    #    hosts:
    #      - shogun.local
  postgres:
    host:
    credentialsSecret:
    credentialsSecretKeyPassword:
  keycloak:
    host: shogun-keycloak.default.svc.cluster.local

shogun-client:
  enabled: true
  ingress:
    enabled: true
    className: ""
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: shogun.local
        paths:
          - path: /client(/|$)(.*)
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: shogun-tls
    #    hosts:
    #      - shogun.local

postgis:
  enabled: true
  postgres:
    database: shogun
    username: shogun
    customInit:
      enabled: true
      username: keycloak
      databases:
        - keycloak

geoserver:
  enabled: true
  ingress:
    enabled: true
    annotations:
      spec.ingressClassName: nginx
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
    hosts:
      - host: shogun.local
        paths: [ "/geoserver" ]
    tls: []
      # - secretName: geoserver-secret
      #   hosts:
    #     - shogun.local

keycloak:
  enabled: true
  production: true
  proxy: edge
  postgresql:
    enabled: false
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: '--import-realm'
    - name: SHOGUN_WEBHOOK_URIS
      value: "http://{{ .Release.Name }}-shogun-boot.{{ .Release.Namespace }}.svc.cluster.local:8080/webhooks/keycloak"
  initContainers:
    - name: keycloak-data-container
      image: docker-public.terrestris.de/shogun/keycloak-data:1.0
      command: ['cp', '/keycloak_export.json', '/share']
      volumeMounts:
        - name: realm-import
          mountPath: "/share"
    - name: keycloak-event-listener-container
      image: docker-public.terrestris.de/shogun/keycloak-event-listener:1.0
      command: ['cp', '/event-listener-shogun-jar-with-dependencies.jar', '/opt/bitnami/keycloak/providers/event-listener-shogun-jar-with-dependencies.jar']
      volumeMounts:
        - name: providers
          mountPath: /opt/bitnami/keycloak/providers
  extraVolumes:
    - name: realm-import
      emptyDir: {}
    - name: providers
      emptyDir: {}
  extraVolumeMounts:
    - name: realm-import
      mountPath: /opt/bitnami/keycloak/data/import
    - name: providers
      mountPath: /opt/bitnami/keycloak/providers
  externalDatabase:
    host: "{{ .Release.Name }}-postgis"
    user: keycloak
    database: keycloak
    existingSecret: "{{ .Release.Name }}-postgis-keycloak-credentials"
    existingSecretPasswordKey: custom-user-password

mapfish-print:
  enabled: true
