apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
{{ include "geoserver.labels" . | indent 4 }}
data:
  init-data.sh: |-
    #!/bin/sh
    echo "Checking if geoserver_data is already initialized…"
    FILE={{ .Values.storage.dataDir }}/.init
    if [ -f "$FILE" ]; then
      echo "Directory geoserver_data already initialized."
    else
      echo "Downloading geoserver_data.tgz …"
      CMD="wget -q -O /mnt/download/geoserver_data.tgz '{{ .Values.storage.initDataUrl }}'"
      echo $CMD
      eval $CMD
      CMD="cd {{ .Values.storage.dataDir }}"
      echo $CMD
      eval $CMD
      CMD="tar -zxf /mnt/download/geoserver_data.tgz --strip 1 -k"
      echo $CMD
      eval $CMD
      CMD="touch $FILE"
      echo $CMD
      eval $CMD
      echo "Successfully extracted geoserver_data directory to '{{ .Values.storage.dataDir }}'!"
    fi
