apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mapproxy.fullname" . }}
  labels:
    {{- include "mapproxy.labels" . | nindent 4 }}
data:
  mapproxy.yaml: |-
    # -------------------------------
    # MapProxy configuration.
    #
    # OSM example based on https://wiki.openstreetmap.org/wiki/MapProxy
    # -------------------------------
    services:
      demo:
      wmts:
      wms:
        srs: ['EPSG:3857']

    layers:
      - name: osm-terrestris
        title: OpenStreetMap WMS by terrestris
        sources: [osm_terrestris_cache]

    caches:
      osm_terrestris_cache:
        sources: [osm_terrestris]
        grids: [osm_terrestris_grid]
        format: image/png
        cache:
          type: sqlite
          directory: /mapproxy/config/cache_data/osm_terrestris_cache

    sources:
      osm_terrestris:
        type: wms
        req:
          url: https://ows.terrestris.de/osm/service
          transparent: true
          layers: OSM-WMS

    grids:
      osm_terrestris_grid:
        srs: EPSG:3857
        origin: nw

    globals:
      cache:
        base_dir: '/mapproxy/config/cache_data'
        lock_dir: '/mapproxy/config/cache_data/locks'
        tile_lock_dir: '/mapproxy/config/cache_data/tile_locks'
    image:
      resampling_method: bicubic
  seed.yaml: |-
    seeds:
      osm_terrestris_cache:
        caches: [osm_terrestris_cache]
        refresh_before:
          weeks: 1
