apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mapproxy.fullname" . }}
  labels:
    {{- include "mapproxy.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mapproxy.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mapproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mapproxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mapproxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mapproxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.url }}
              port: {{ .Values.livenessProbe.port }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.url }}
              port: {{ .Values.readinessProbe.port }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.url }}
              port: {{ .Values.startupProbe.port }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          {{- end }}
          volumeMounts:
            - name: cache-datadir
              mountPath: /mapproxy/config/cache_data/
            {{- if and .Values.customMapproxyConfig.enabled }}
            - name: custom-mapproxy-yaml
              mountPath: /mapproxy/config/mapproxy.yaml
              subPath: mapproxy.yaml
            {{- else }}
            - name: {{ include "mapproxy.fullname" . }}-mapproxy-yaml
              mountPath: /mapproxy/config/mapproxy.yaml
              subPath: mapproxy.yaml
            {{- end }}
            {{- if and .Values.customSeedConfig.enabled }}
            - name: custom-seed-yaml
              mountPath: /mapproxy/config/seed.yaml
              subPath: seed.yaml
            {{- else }}
            - name: {{ include "mapproxy.fullname" . }}-seed-yaml
              mountPath: /mapproxy/config/seed.yaml
              subPath: mapproxy.yaml
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if and .Values.customMapproxyConfig.enabled }}
        - name: custom-mapproxy-yaml
          configMap:
            name: {{ .Values.customMapproxyConfig.configMapName }}
        {{- else}}
        - name: {{ include "mapproxy.fullname" . }}-mapproxy-yaml
          configMap:
            name: {{ include "mapproxy.fullname" . }}
        {{- end }}
        {{- if .Values.customSeedConfig.enabled }}
        - name: custom-seed-yaml
          configMap:
            name: {{ .Values.customSeedConfig.configMapName }}
        {{- else}}
        - name: {{ include "mapproxy.fullname" . }}-seed-yaml
          configMap:
            name: {{ include "mapproxy.fullname" . }}
        {{- end }}
        {{- if and .Values.persistence.enabled (not .Values.persistence.useExisting) }}
        - name: cache-datadir
          persistentVolumeClaim:
            claimName: {{ include "mapproxy.fullname" . }}
        {{- else if and .Values.persistence.useExisting (.Values.persistence.existingPvcName) }}
        - name: cache-datadir
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingPvcName }}
        {{- else }}
        - name: cache-datadir
          emptyDir: {}
        {{- end }}
