---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shogun-client.fullname" . }}
  labels:
{{ include "shogun-client.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "shogun-client.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- if .Values.logs.enabled }}
        fluentd: "true"
        {{- end }}
{{ include "shogun-client.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: "/usr/share/nginx/html/gis-client-config.js"
              subPath: gis-client-config.js
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "shogun-client.fullname" . }}
            items:
              - key: gis-client-config
                path: "gis-client-config.js"
      {{- with .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- range .Values.hostAliases }}
      hostAliases:
        - ip: {{ .ip | quote }}
          hostnames:
            {{- range .hostnames }}
            - {{ .hostname }}
            {{- end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
