# Default values for postgis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.terrestris.de/postgis/postgis
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

postgres:
  database: postgres
  username: postgres
  existingSecret:
    enabled: false
  # conf: |
  #   listen_addresses = '*'
  #   jit = off
  customInit:
    enabled: false
    username: my-user
    databases:
      - my-database

persistence:
  enabled: false
  useExisting: false
  existingPvcName: ""
  size: 8Gi
  accessMode: ReadWriteOnce
  storageClassName: ""

dataImport:
  enabled: false
  initDataUrl: https://files.example.com/postgresql_data.tar.gz

# extraInitEnvFrom: |
#   - secretRef:
#       name: initdatacred

# extraEnvFrom:

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 3 # default timeout of pg_isready

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 3 # default timeout of pg_isready

startupProbe:
  enabled: false
  initialDelaySeconds: 60
  timeoutSeconds: 1
  failureThreshold: 15
  periodSeconds: 5
