apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "mapfish-print.labels" . | indent 4 }}
  name: {{ include "mapfish-print.fullname" . }}
data:
  init-printapps.sh: |-
    #!/bin/sh
    apk add --no-cache wget
    echo "Initializing print apps"
    FILE={{ .Values.storage.printConfigDir }}/.init
    if [ -f "$FILE" ]; then
      echo "Print apps already initialized"
    else
      echo "Downloading print apps"
      if ([ -z "$PRINTCONFIG_USER" ] || [ -z "$PRINTCONFIG_PASSWORD" ]); then
        echo "Downloading without credentials…"
        CMD="wget -q -O /mnt/download/printapps.tar.gz '{{ .Values.storage.printAppsUrl }}'"
      else
        echo "Downloading with credentials…"
        CMD="wget --user $PRINTCONFIG_USER --password $PRINTCONFIG_PASSWORD -q -O /mnt/download/printapps.tar.gz '{{ .Values.storage.printAppsUrl }}'"
      fi
      eval $CMD
      CMD="cd {{ .Values.storage.printConfigDir }}"
      echo $CMD
      eval $CMD
      CMD="tar xvf /mnt/download/printapps.tar.gz"
      echo $CMD
      eval $CMD
      CMD="touch $FILE"
      echo $CMD
      eval $CMD
      echo "Successfully extracted print apps to '{{ .Values.storage.printConfigDir }}'!"
    fi
