replicaCount: 1

logs:
  enabled: true

image:
  repository: docker-public.terrestris.de/terrestris/shogun-gis-client
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: vault-issuer
  hosts:
    - host: shogun-client.example.com
      paths: [ "/" ]
  tls:
    - secretName: shogun-client-tls
      hosts:
        - shogun-client.example.com

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 256Mi

keycloak:
  host: shogun-keycloak
  realm: SHOGun
  clientId: shogun-client
  onLoadAction: login-required

shogun:
  base: shogun-boot.example.com

print:
  base: mapfish-print.example.com

nodeSelector: {}

tolerations: []

affinity: {}
