replicaCount: 1

logs:
  enabled: true

image:
  repository: docker-public.terrestris.de/terrestris/shogun-admin
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: vault-issuer
  hosts:
    - host: shogun-admin.example.com
      paths: [ "/" ]
  tls:
    - secretName: shogun-admin-tls
      hosts:
        - shogun-admin.example.com

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 256Mi

shogun:
  appPrefix: ""
  base: https://shogun-boot.example.com

keycloak:
  host: keycloak.example.com
  realm: SHOGun
  clientId: shogun-admin
  authorizedAdminRole: admin

client:
  base: https://shogun-client.example.com

geoserver:
  url: https://geoserver.example.com

nodeSelector: {}

tolerations: []

affinity: {}
