apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "shogun-admin.labels" . | indent 4 }}
  name: {{ include "shogun-admin.fullname" . }}
data:
  admin-client-config: |-
    var shogunApplicationConfig = {
      appPrefix: '{{ .Values.shogun.appPrefix }}',
      path: {
        modelConfigs: '{{ .Values.shogun.appPrefix }}/modelconfigs',
        shogunBase: '{{ .Values.shogun.base }}/',
        logo: null
      },
      security: {
        keycloak: {
          enabled: true,
          host: 'https://{{ .Values.keycloak.host }}',
          realm: '{{ .Values.keycloak.realm }}',
          clientId: '{{ .Values.keycloak.clientId }}',
          authorizedRoles: [
            '{{ .Values.keycloak.authorizedAdminRole }}'
          ]
        }
      },
      geoserver: {
        base: '{{ .Values.geoserver.url }}',
        upload: {
          workspace: 'SHOGUN',
          limit: 5000000000
        }
      },
      models: [
        'Application',
        'Layer'
      ],
      dashboard: {
        news: {
          visible: true
        },
        statistics: {
          visible: false
        },
        applications: {
          visible: false
        },
        layers: {
          visible: true
        },
        users: {
          visible: false
        }
      },
      navigation: {
        general: {
          imagefiles: {
            visible: false
          }
        },
        status: {
          metrics: {
            visible: true
          },
          logs: {
            visible: true
          }
        },
        settings: {
          global: {
            visible: true
          },
          logs: {
            visible: true
          }
        }
      }
    };
  index-html: |-
    <!DOCTYPE html>
    <html lang="de">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="user-scalable=no,width=device-width,initial-scale=1,shrink-to-fit=no" />
        <title>SHOGun admin</title>
        <base href="{{ .Values.shogun.appPrefix }}/" />
        <link rel="icon" href="favicon.ico?13e260e94e2e3f8104da" />
        <script defer="defer" src="{{ .Values.shogun.appPrefix }}/js/main.bundle.js?13e260e94e2e3f8104da"></script>
      </head>
      <body>
        <noscript>You need to enable JavaScript to run this app.</noscript>
        <div id="app" class="app" style="height: 100%; width: 100%;"></div>
        <script src="{{ .Values.shogun.appPrefix }}/config/admin-client-config.js"></script>
        <script>
          if (!window.shogunApplicationConfig) {
            console.warn("No SHOGun application config found. Loading fallback.");
            document.write('<script src="{{ .Values.shogun.appPrefix }}/fallbackConfig.js"><\/script>');
          }
        </script>
      </body>
    </html>
  application-config: |-
    {
      "i18n": {
        "de": {
          "entityName": "Instanz",
          "navigationTitle": "Instanzen",
          "labelID": "Identifier",
          "labelEstabl": "Erstellt am",
          "labelEdit": "Zuletzt editiert am",
          "labelName": "Name",
          "labelWork": "Arbeitsstand",
          "labelClientConfig": "Client-Konfiguration",
          "labelTree": "Themenbaum",
          "labelLayerConfig": "Layer-Konfiguration",
          "labelToolConfig": "Werkzeug-Konfiguration",
          "labelUserPermissions": "Nutzerberechtigungen",
          "titleId": "ID",
          "titleName": "Name",
          "titleEdit": "Zuletzt editiert am",
          "titleLink": "Link zur Instanz",
          "toolTipLink": "Öffne Instanz"
        },
        "en": {
          "entityName": "Instance",
          "navigationTitle": "Instance",
          "labelID": "Identifier",
          "labelEstabl": "Created at",
          "labelEdit": "Last edited on",
          "labelName": "Name",
          "labelWork": "Status of work",
          "labelClientConfig": "Client configuration",
          "labelTree": "Layertree",
          "labelLayerConfig": "Layer configuration",
          "labelToolConfig": "Configure Tools",
          "labelUserPermissions": "User permissions",
          "titleId": "ID",
          "titleName": "Name",
          "titleEdit": "Last edited on",
          "titleLink": "Link to instance",
          "toolTipLink": "Open instance"
        }
      },
      "endpoint": "{{ .Values.shogun.base }}/applications",
      "entityType": "application",
      "entityName": "#i18n.entityName",
      "navigationTitle": "#i18n.navigationTitle",
      "subTitle": "",
      "formConfig": {
        "name": "application",
        "fields": [
          {
            "dataType": "number",
            "dataField": "id",
            "label": "#i18n.labelID",
            "readOnly": "true"
          },
          {
            "dataField": "created",
            "dataType": "date",
            "readOnly": "true",
            "component": "DateField",
            "label": "#i18n.labelEstabl",
            "fieldProps": {
              "dateFormat": "DD.MM.YYYY HH:mm"
            }
          },
          {
            "dataField": "modified",
            "dataType": "date",
            "readOnly": "true",
            "label": "#i18n.labelEdit",
            "component": "DateField",
            "fieldProps": {
              "dateFormat": "DD.MM.YYYY HH:mm"
            }
          },
          {
            "component": "Input",
            "dataField": "name",
            "label": "#i18n.labelName",
            "required": "true"
          },
          {
            "component": "Switch",
            "dataField": "stateOnly",
            "label": "#i18n.labelWork",
            "readOnly": "true"
          },
          {
            "component": "JSONEditor",
            "dataField": "clientConfig",
            "label": "#i18n.labelClientConfig",
            "fieldProps": {}
          },
          {
            "component": "JSONEditor",
            "dataField": "layerTree",
            "label": "#i18n.labelTree",
            "fieldProps": {}
          },
          {
            "component": "JSONEditor",
            "dataField": "layerConfig",
            "label": "#i18n.labelLayerConfig",
            "fieldProps": {}
          },
          {
            "component": "JSONEditor",
            "dataField": "toolConfig",
            "label": "#i18n.labelToolConfig",
            "fieldProps": {}
          },
          {
            "component": "UserPermissionGrid",
            "label": "#i18n.labelUserPermissions",
            "fieldProps": {}
          }
        ]
      },
      "tableConfig": {
        "columnDefinition": [
          {
            "title": "#i18n.titleId",
            "dataIndex": "id",
            "sortConfig": {
              "isSortable": true,
              "defaultSortOrder": "descend"
            }
          },
          {
            "title": "#i18n.titleName",
            "dataIndex": "name",
            "key": "name",
            "sortConfig": {
              "isSortable": false
            },
            "filterConfig": {
              "isFilterable": true
            }
          },
          {
            "title": "#i18n.titleEdit",
            "dataIndex": "modified",
            "key": "modified",
            "sortConfig": {
              "isSortable": true
            },
            "cellRenderComponentName": "DateCell"
          },
          {
            "title": "#i18n.titleLink",
            "dataIndex": "id",
            "key": "link",
            "cellRenderComponentName": "LinkCell",
            "cellRenderComponentProps": {
              "title": "#i18n.toolTipLink",
              "template": "{{ .Values.client.base }}/?applicationId={}"
            }
          }
        ]
      }
    }
  layer-config: |-
    {
      "i18n": {
        "de": {
          "entityName": "Thema",
          "navigationTitle": "Themen",
          "labelId": "ID",
          "labelEstabl": "Erstellt am",
          "labelEdit": "Zuletzt editiert am",
          "labelName": "Name",
          "labelType": "Typ",
          "labelConfig": "Konfiguration",
          "labelSource": "Datenquelle",
          "titleId": "ID",
          "titleName": "Name",
          "titleType": "Typ",
          "titlePrev": "Layervorschau"
        },
        "en": {
          "entityName": "Subject",
          "navigationTitle": "Subjects",
          "labelId": "ID",
          "labelEstabl": "Created at",
          "labelEdit": "Last edited on",
          "labelName": "Name",
          "labelType": "Type",
          "labelConfig": "Configuration",
          "labelSource": "Datasource",
          "titleId": "ID",
          "titleName": "Name",
          "titleType": "Type",
          "titlePrev": "Layer preview"
        }
      },
      "endpoint": "{{ .Values.shogun.base }}/layers",
      "entityType": "layer",
      "entityName": "#i18n.entityName",
      "navigationTitle": "#i18n.navigationTitle",
      "subTitle": "",
      "formConfig": {
        "name": "layer",
        "fields": [
          {
            "dataType": "number",
            "dataField": "id",
            "label": "#i18n.labelId",
            "readOnly": "true"
          },
          {
            "dataField": "created",
            "dataType": "date",
            "readOnly": "true",
            "component": "DateField",
            "label": "#i18n.labelEstabl",
            "fieldProps": {
              "dateFormat": "DD.MM.YYYY HH:mm"
            }
          },
          {
            "dataField": "modified",
            "dataType": "date",
            "readOnly": "true",
            "label": "#i18n.labelEdit",
            "component": "DateField",
            "fieldProps": {
              "dateFormat": "DD.MM.YYYY HH:mm"
            }
          },
          {
            "component": "Input",
            "dataField": "name",
            "label": "#i18n.labelName",
            "required": "true"
          },
          {
            "component": "LayerTypeSelect",
            "dataField": "type",
            "label": "#i18n.labelType",
            "required": "true"
          },
          {
            "component": "JSONEditor",
            "dataField": "clientConfig",
            "label": "#i18n.labelConfig",
            "fieldProps": {}
          },
          {
            "component": "JSONEditor",
            "dataField": "sourceConfig",
            "label": "#i18n.labelSource",
            "fieldProps": {}
          }
        ]
      },
      "tableConfig": {
        "columnDefinition": [
          {
            "title": "#i18n.titleId",
            "dataIndex": "id",
            "sortConfig": {
              "isSortable": false
            }
          },
          {
            "title": "#i18n.titleName",
            "dataIndex": "name",
            "key": "name",
            "sortConfig": {
              "isSortable": true
            },
            "filterConfig": {
              "isFilterable": true
            }
          },
          {
            "title": "#i18n.titleType",
            "dataIndex": "type",
            "key": "type",
            "sortConfig": {
              "isSortable": true
            }
          },
          {
            "title": "#i18n.titlePrev",
            "key": "preview",
            "cellRenderComponentName": "LayerPreviewCell"
          }
        ]
      }
    }
