{{- if and .Values.persistence.enabled (not .Values.persistence.useExisting) -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "postgis.fullname" . }}
  labels:
    {{- include "postgis.labels" . | nindent 4 }}
spec:
  {{- if and .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
