{{- $postgresPassword := include "postgis.secrets.lookup" (dict "secret" (include "postgis.defaultuser.secretname" .) "key" ( printf "%s-password" (tpl .Values.postgres.username $)) "defaultValue" (randAlphaNum 19) "context" $) | trimAll "\"" | b64dec }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgis.defaultuser.secretname" . }}
  labels:
{{ include "postgis.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.postgres.password }}
  {{ .Values.postgres.username }}-password: {{ .Values.postgres.password | b64enc | quote }}
{{- else }}
  {{ .Values.postgres.username }}-password: {{ $postgresPassword | b64enc | quote }}
{{- end}}
