{{- if .Values.postgres.customInit.enabled }}
{{- $postgresPassword := include "postgis.secrets.lookup" (dict "secret" (include "postgis.custominit.secretname" .) "key" ( printf "%s-password" (tpl .Values.postgres.username $)) "defaultValue" (randAlphaNum 19) "context" $) | trimAll "\"" | b64dec }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgis.custominit.secretname" . }}
  labels:
{{ include "postgis.labels" . | indent 4 }}
type: Opaque
data:
  {{- with .Values.postgres.customInit.username }}
  custom-user-password: {{ $postgresPassword | b64enc | quote }}
  {{- end }}
{{- end }}
