{{- if not .Values.postgres.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgis.fullname" . }}-{{ .Values.postgres.username }}-credentials
  labels:
{{ include "postgis.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.postgres.password }}
  {{ .Values.postgres.username }}-password: {{ .Values.postgres.password | b64enc | quote }}
{{- else }}
  {{ .Values.postgres.username }}-password: {{ randAlphaNum 19 | b64enc | quote }}
{{- end}}
{{- end}}
