{{- if .Values.postgres.customInit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgis.fullname" . }}-{{ .Values.postgres.customInit.username }}-credentials
  labels:
{{ include "postgis.labels" . | indent 4 }}
type: Opaque
data:
  {{- with .Values.postgres.customInit.username }}
  custom-user-password: {{ randAlphaNum 19 | b64enc | quote }}
  {{- end }}
{{- end }}
