apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gnos.fullname" . }}
  labels:
{{ include "gnos.labels" . | indent 4 }}
data:
  jdbc.properties: |-
    jdbc.username={{ .Values.db.username }}
    jdbc.password={{ .Values.db.password }}
    jdbc.database={{ .Values.db.name }}
    jdbc.host={{ .Values.db.host }}
    jdbc.port={{ .Values.db.port }}
    jdbc.connectionProperties=#{systemEnvironment['GEONETWORK_DB_CONNECTION_PROPERTIES']}
    jdbc.basic.removeAbandoned=true
    jdbc.basic.removeAbandonedTimeout=300
    jdbc.basic.logAbandoned=true
    jdbc.basic.maxActive=30
    jdbc.basic.maxIdle=10
    jdbc.basic.initialSize=10
    jdbc.basic.maxWait=500
    jdbc.basic.testOnBorrow=true
    jdbc.basic.timeBetweenEvictionRunsMillis=1000
    jdbc.basic.minEvictableIdleTimeMillis=1800000
    jdbc.basic.testWhileIdle=true
    jdbc.basic.numTestsPerEvictionRun=5
    jdbc.basic.poolPreparedStatements=true
    jdbc.basic.maxOpenPreparedStatements=1200
    jdbc.basic.validationQuery=SELECT 1
    jdbc.basic.defaultReadOnly=false
    jdbc.basic.defaultAutoCommit=false
