apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elk.name }}
spec:
  version: {{ .Values.elk.version }}
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
