apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.elk.name }}-kibana
spec:
  version: {{ .Values.elk.version }}
  count: 1
  elasticsearchRef:
    name: {{ .Values.elk.name }}
